test:
  adapter: mysql2
  database: open_protocol_test
  socket:
  username:
  password:
  timeout: 5000

development:
  adapter: mysql2
  database: open_protocol
  socket:
  username:
  password:
  timeout: 5000

staging:
  
production:
  